# fly.toml app configuration file generated for my-remix-app-wispy-sea-4995 on 2024-08-05T10:39:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-remix-app-wispy-sea-4995'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
